# Generated by Django 6.0.4 on 2026-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
    ]
