# Generated by Django 6.0.4 on 2026-05-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
    ]
